version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.107.0
    configs:
    - source: otel_collector_conf
      target: /etc/otelcol/config.yaml
    ports:
    - "4318:4318"
    - "8889:8889"
  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
    - "16686:16686"
  prometheus:
    image: prom/prometheus:v2.54.0
    configs:
    - source: prometheus_conf
      target: /etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
  loki:
    image: grafana/loki:3.1.1
  grafana:
    image: grafana/grafana:11.2.0
    configs:
    - source: grafana_conf
      target: /etc/grafana/grafana.ini
    - source: grafana_datasources
      target: /etc/grafana/provisioning/datasources/datasources.yml
    - source: grafana_dashboards
      target: /etc/grafana/provisioning/dashboards/dashboards.yml
    - source: grafana_sample_dashboard
      target: /etc/grafana/provisioning/dashboards/sample.json
    ports:
    - "3000:3000"

configs:
  otel_collector_conf:
    content: |
      receivers:
        otlp:
          protocols:
            http:
              endpoint: ":4318"
      exporters:
        otlphttp/jaeger:
          endpoint: http://jaeger:4318
        prometheus:
          endpoint: ":8889"
        otlphttp/loki:
          endpoint: http://loki:3100/otlp
      processors:
        batch:
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/jaeger]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp/loki]
  prometheus_conf:
    content: |
      global:
        scrape_interval: 5s
      scrape_configs:
      - job_name: "otel-collector"
        scrape_interval: 10s
        static_configs:
        - targets: ["otel-collector:8889"]
  grafana_conf:
    content: |
      [auth.anonymous]
      enabled = true
      org_role = Admin
  grafana_datasources:
    content: |
      apiVersion: 1
      datasources:
      - uid: prometheus
        name: Prometheus
        type: prometheus
        access: proxy
        url: http://host.docker.internal:9090
        editable: false
        jsonData:
          httpMethod: POST
      - uid: jaeger
        name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
        jsonData:
          tracesToLogsV2:
            datasourceUid: "loki"
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
            tags:
            - key: "service.instance.id"
              value: "service_instance_id"
            customQuery: true
            query: "{$$$${__tags}} | trace_id=`$$$${__trace.traceId}`"
      - uid: loki
        name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          derivedFields:
          - datasourceUid: jaeger
            name: trace_id
            matcherType: label
            matcherRegex: trace_id
            url: "$$$${__value.raw}"
            urlDisplayLabel: "View Trace"
  grafana_dashboards:
    content: |
      apiVersion: 1
      providers:
      - name: dashboards
        type: file
        options:
          path: /etc/grafana/provisioning/dashboards
          foldersFromFilesStructure: true
  grafana_sample_dashboard:
    content: |
      {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "datasource",
                "uid": "grafana"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "target": {
                "limit": 100,
                "matchAny": false,
                "tags": [],
                "type": "dashboard"
              },
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "id": 5,
        "links": [],
        "liveNow": false,
        "panels": [
          {
            "datasource": {
              "default": true,
              "type": "prometheus",
              "uid": "prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "id": 60,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "editorMode": "code",
                "expr": "increase(http_server_request_duration_seconds_count{exported_job=\"$$service_name\"}[1m])",
                "instant": false,
                "legendFormat": "{{http_request_method}} {{http_route}}",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "\"$$service_name\" - HTTP requests count, 1min",
            "type": "timeseries"
          },
          {
            "datasource": {
              "default": true,
              "type": "prometheus",
              "uid": "prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineStyle": {
                    "fill": "solid"
                  },
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "unit": "s"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            },
            "id": 61,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "editorMode": "code",
                "expr": "sum(increase(http_server_request_duration_seconds_sum{exported_job=\"$$service_name\"}[5m])) by (http_request_method, http_route)\r\n/\r\nsum(increase(http_server_request_duration_seconds_count{exported_job=\"$$service_name\"}[5m])) by (http_request_method, http_route)",
                "instant": false,
                "legendFormat": "{{http_request_method}} {{http_route}}",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "\"$$service_name\" - HTTP requests avg 5 min response time , sec",
            "type": "timeseries"
          },
          {
            "datasource": {
              "default": true,
              "type": "prometheus",
              "uid": "prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                }
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            },
            "id": 62,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "editorMode": "code",
                "expr": "increase(db_client_connections_use_time_milliseconds_count{exported_job=\"$$service_name\"}[1m])",
                "instant": false,
                "legendFormat": "requests",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "\"$$service_name\" - Database queries count, 1min",
            "type": "timeseries"
          },
          {
            "datasource": {
              "default": true,
              "type": "prometheus",
              "uid": "prometheus"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisBorderShow": false,
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "barWidthFactor": 0.6,
                  "drawStyle": "line",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "unit": "ms"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 8
            },
            "id": 63,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "prometheus"
                },
                "editorMode": "code",
                "expr": "sum(increase(db_client_connections_use_time_milliseconds_sum{exported_job=\"$$service_name\"}[5m]))\r\n/\r\nsum(increase(db_client_connections_use_time_milliseconds_count{exported_job=\"$$service_name\"}[5m]))",
                "instant": false,
                "legendFormat": "request time",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "\"$$service_name\" - Database queries avg 5 min duration , sec",
            "type": "timeseries"
          }
        ],
        "refresh": "",
        "schemaVersion": 39,
        "tags": [
          "overview",
          "main",
          "sync"
        ],
        "templating": {
          "list": [
            {
              "current": {
                "selected": false,
                "text": "event-service",
                "value": "event-service"
              },
              "datasource": {
                "type": "prometheus",
                "uid": "prometheus"
              },
              "definition": "label_values(exported_job)",
              "hide": 0,
              "includeAll": false,
              "multi": false,
              "name": "service_name",
              "options": [],
              "query": {
                "qryType": 1,
                "query": "label_values(exported_job)",
                "refId": "PrometheusVariableQueryEditor-VariableQuery"
              },
              "refresh": 1,
              "regex": "",
              "skipUrlSync": false,
              "sort": 0,
              "type": "query"
            }
          ]
        },
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {
          "refresh_intervals": [
            "5s",
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
          ],
          "time_options": [
            "5m",
            "15m",
            "1h",
            "6h",
            "12h",
            "24h",
            "2d",
            "7d",
            "30d"
          ]
        },
        "timezone": "",
        "title": "Sample",
        "uid": "XZNh5I-mk",
        "version": 17,
        "weekStart": ""
      }